### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by wangdi18** [ht0Ruial/TomatoTools#2]
python ./TomatoTools.py
出现以下报错：
qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

**Comment by ht0Ruial** [comment]
:grin:建议先将python安装目录下的 _**\**\Lib\site-packages\PyQt5\Qt5\plugins**_ 添加到环境变量中再试试
