### ISSUE TITLE
凯撒解密可能错了，与其他解密软件结果不同

### ISSUE THREAD

**Issue by 866666** [ht0Ruial/TomatoTools#3]
XMZFSLDZ 的凯撒结果是
YNBGTMEB
AOCHUNFC
BPDIVOGD
CQEJWPHE
DRFKXQIF
ESGLYRJG
FTHMASKH
GUINBTLI
HVJOCUMJ
IWKPDVNK
JXLQEWOL
KYMRFXPM
LANSGYQN
MBOTHARO
NCPUIBSP
ODQVJCTQ
PERWKDUR
QFSXLEVS
RGTYMFWT
SHUANGXU
TIVBOHYV
UJWCPIAW
VKXDQJBX
WLYERKCY
XMAFSLDA

而其他软件计算结果是：
YNAGTMEA
ZOBHUNFB
APCIVOGC
BQDJWPHD
CREKXQIE
DSFLYRJF
ETGMZSKG
FUHNATLH
GVIOBUMI
HWJPCVNJ
IXKQDWOK
JYLREXPL
KZMSFYQM
LANTGZRN
MBOUHASO
NCPVIBTP
ODQWJCUQ
PERXKDVR
QFSYLEWS
RGTZMFXT
SHUANGYU   
TIVBOHZV
UJWCPIAW
VKXDQJBX
WLYERKCY

**Comment by ht0Ruial** [comment]
:grin:感谢指正:+1:
