### ISSUE TITLE
请教一下大佬

### ISSUE THREAD

**Issue by FCB-Barcelona** [ht0Ruial/TomatoTools#6]
请问可以在linux里面运行吗？尝试了一下都失败了

**Comment by ht0Ruial** [comment]
首先，TomatoTools 能在linux里运行；

然后，我猜测你失败的原因：
1.   没有正确安装所需的依赖库；

>  

你需要检查 requirements 的库有没有正确安装；

2. 由于linux默认的python命令指向的是python2；

> 

你需要用python3来启用TomatoTools，例如，python3 TomatoTools.py ；
