### ISSUE TITLE
 摩斯解码 的bug

### ISSUE THREAD

**Issue by Asteri5m** [ht0Ruial/TomatoTools#7]
你好，在使用过程中发现 摩斯解码 的bug，对于 / 分隔的密文解码错误，通过查看您的源码发现您的代码如下
Crypto_func.py  283行

> def de_Morse(cryptostr):
    Morse_dic = {
        '-----': '0', '.----': '1', '..---': '2', '...--': '3', '....-': '4', '.....': '5',
        '-....': '6', '--...': '7', '---..': '8', '----.': '9', '.-': 'a', '-...': 'b',
        '-.-.': 'c', '-..': 'd', '.': 'e', '..-.': 'f', '--.': 'g', '....': 'h', '..': 'i',
        '.---': 'j', '-.-': 'k', '.-..': 'l', '--': 'm', '-.': 'n', '---': 'o', '.--.': 'p',
        '--.-': 'q', '.-.': 'r', '...': 's', '-': 't', '..-': 'u', '...-': 'v', '.--': 'w',
        '-..-': 'x', '-.--': 'y', '--..': 'z', '--.....': '`', '------.': '~', '-.-.--': '!',
        '.--.-.': '@', '-...--': '#', '.-...': '&', '...-..-': '$', '-..-.-': '%', '-.----.': '^',
        '-.-.-.': ';', '-.--.': '(', '-.--.-': ')', '-....-': '-', '..--.-': '_', '-...-': '=',
        '.-.-.': '+', '-.--.--': '[', '-.---.-': ']', '----.--': '{', '-----.-': '}',
        '---...': ':', '.----.': "'", '.-..-.': '"', '--..--': ',', '.-.-.-': '.', '----..': '<',
        '-----.': '>', '-..-.': '/', '..--..': '?'
    }
    if '/' in cryptostr:
        cryptostr.replace('/', ' ')  #这里的替换未生效
    cc = []
    for i in cryptostr.lower().split(' '):
        cc.append(Morse_dic.get(i))
    result = ''.join(cc).encode()
    return result

其中需要修改的部分为：

>   if '/' in cryptostr:
        cryptostr = cryptostr.replace('/', ' ') `

**Comment by ht0Ruial** [comment]
😁感谢指正，respect👍
